name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Comprobar el código
      - name: Checkout code
        uses: actions/checkout@v2

      # Autenticarse en Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Construir la imagen con el nombre correcto (Reemplaza "miusuario" por tu nombre real de Docker Hub)
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/google-remote-desktop:latest .

      # Push de la imagen a Docker Hub (Asegúrate de que el nombre coincide con el de la construcción)
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/google-remote-desktop:latest
