name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Comprobar el código
      - name: Checkout code
        uses: actions/checkout@v2

      # Autenticarse en Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Construir la imagen
      - name: Build Docker image
        run: docker build -t camilocuaddros2/virtualdesktop .

      # Push de la imagen a Docker Hub
      - name: Push Docker image
        run: docker push camilocuadros2/virtualdesktop
