name: Docker Image CI

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t <TU_USUARIO>/my-docker-image .

    - name: Push Docker image to Docker Hub
      run: docker push <TU_USUARIO>/my-docker-image
